Fri, 03 Jan 2020 11:19:46 - INFO - Connect to DB
Fri, 03 Jan 2020 11:19:46 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:19:46 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:20:41 - INFO - Connect to DB
Fri, 03 Jan 2020 11:20:41 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:20:41 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:20:52 - INFO - Connect to DB
Fri, 03 Jan 2020 11:20:52 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:20:52 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:21:03 - INFO - Connect to DB
Fri, 03 Jan 2020 11:21:03 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:21:03 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:21:09 - INFO - Connect to DB
Fri, 03 Jan 2020 11:21:09 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:21:09 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:21:14 - INFO - Connect to DB
Fri, 03 Jan 2020 11:21:14 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:21:15 - INFO - Failed on TRIZMA DB import at: 2020-01-03_11-19-46, for following calling party: 4991618829098, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht 端bermittelt','trz_madamovic',                                  '4991618829098','','Nicht 端bermittelt','4991618829098_Monday, December 30, 2019_10:11:30 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 11:21:15 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:21:20 - INFO - Connect to DB
Fri, 03 Jan 2020 11:21:20 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:21:20 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:21:26 - INFO - Connect to DB
Fri, 03 Jan 2020 11:21:26 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:21:26 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:26:46 - INFO - Connect to DB
Fri, 03 Jan 2020 11:26:46 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:26:46 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:27:42 - INFO - Connect to DB
Fri, 03 Jan 2020 11:27:42 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:27:42 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:28:20 - INFO - Connect to DB
Fri, 03 Jan 2020 11:28:20 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:28:20 - INFO - Failed on TRIZMA DB import at: 2020-01-03_11-19-46, for following calling party: 4935232328986, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht 端bermittelt','trz_madamovic',                                  '4935232328986','','Nicht 端bermittelt','4935232328986_Tuesday, December 31, 2019_9:34:26 AM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Fri, 03 Jan 2020 11:28:20 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:28:42 - INFO - Connect to DB
Fri, 03 Jan 2020 11:28:42 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:28:42 - INFO - 123TV DB import
Fri, 03 Jan 2020 11:28:54 - INFO - Connect to DB
Fri, 03 Jan 2020 11:28:54 - INFO - TRIZMA DB import
Fri, 03 Jan 2020 11:28:54 - INFO - 123TV DB import
