Thu, 02 Jan 2020 15:00:25 - INFO - Connect to DB
Thu, 02 Jan 2020 15:00:25 - INFO - TRIZMA DB import
Thu, 02 Jan 2020 15:00:25 - INFO - Failed on TRIZMA DB import at: 2020-01-02_14-52-57, for following calling party: 4922896690091, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                  '4922896690091','','Nicht übermittelt','4922896690091_Thursday, January 02, 2020_4:00:18 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Thu, 02 Jan 2020 15:00:25 - INFO - 123TV DB import
Thu, 02 Jan 2020 15:14:44 - INFO - Connect to DB
Thu, 02 Jan 2020 15:14:44 - INFO - TRIZMA DB import
Thu, 02 Jan 2020 15:14:44 - INFO - 123TV DB import
Thu, 02 Jan 2020 15:43:54 - INFO - Connect to DB
Thu, 02 Jan 2020 15:43:54 - INFO - TRIZMA DB import
Thu, 02 Jan 2020 15:43:54 - INFO - 123TV DB import
Thu, 02 Jan 2020 16:31:45 - INFO - Connect to DB
Thu, 02 Jan 2020 16:31:45 - INFO - TRIZMA DB import
Thu, 02 Jan 2020 16:31:45 - INFO - 123TV DB import
