Tue, 21 Jan 2020 10:15:41 - INFO - Connect to DB
Tue, 21 Jan 2020 10:15:41 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:15:41 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:15:47 - INFO - Connect to DB
Tue, 21 Jan 2020 10:15:47 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:15:47 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:25:26 - INFO - Connect to DB
Tue, 21 Jan 2020 10:25:26 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:25:26 - INFO - Failed on TRIZMA DB import at: 2020-01-21_10-10-56, for following calling party: 499654922842, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                 '499654922842','','Nicht übermittelt','499654922842_Saturday, January 18, 2020_10:35:03 AM','BOR_MAKSIM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Tue, 21 Jan 2020 10:25:26 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:25:53 - INFO - Connect to DB
Tue, 21 Jan 2020 10:25:53 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:25:53 - INFO - Failed on TRIZMA DB import at: 2020-01-21_10-10-56, for following calling party: 4917664778806, for agent id: trz_bmaksimovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_bmaksimovic',                                 '4917664778806','','Nicht übermittelt','4917664778806_Saturday, January 18, 2020_11:51:52 AM','BOR_MAKSIM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Tue, 21 Jan 2020 10:25:53 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:30:48 - INFO - Connect to DB
Tue, 21 Jan 2020 10:30:48 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:30:48 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:32:03 - INFO - Connect to DB
Tue, 21 Jan 2020 10:32:03 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:32:03 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:33:10 - INFO - Connect to DB
Tue, 21 Jan 2020 10:33:10 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:33:10 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:35:34 - INFO - Connect to DB
Tue, 21 Jan 2020 10:35:35 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:35:35 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:42:04 - INFO - Connect to DB
Tue, 21 Jan 2020 10:42:04 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:42:04 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:42:10 - INFO - Connect to DB
Tue, 21 Jan 2020 10:42:10 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:42:10 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:42:40 - INFO - Connect to DB
Tue, 21 Jan 2020 10:42:41 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:42:41 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:43:03 - INFO - Connect to DB
Tue, 21 Jan 2020 10:43:03 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:43:03 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:43:35 - INFO - Connect to DB
Tue, 21 Jan 2020 10:43:35 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:43:35 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:44:24 - INFO - Connect to DB
Tue, 21 Jan 2020 10:44:24 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:44:24 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:44:36 - INFO - Connect to DB
Tue, 21 Jan 2020 10:44:36 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:44:36 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:45:12 - INFO - Connect to DB
Tue, 21 Jan 2020 10:45:12 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:45:12 - INFO - Failed on TRIZMA DB import at: 2020-01-21_10-10-56, for following calling party: 4991334799306, for agent id: trz_madamovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_madamovic',                                 '4991334799306','','Nicht übermittelt','4991334799306_Tuesday, January 21, 2020_11:45:07 AM','MIL_ADAMOV')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Tue, 21 Jan 2020 10:45:12 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:45:21 - INFO - Connect to DB
Tue, 21 Jan 2020 10:45:21 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:45:21 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:45:43 - INFO - Connect to DB
Tue, 21 Jan 2020 10:45:43 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:45:43 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:46:14 - INFO - Connect to DB
Tue, 21 Jan 2020 10:46:14 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:46:14 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:46:27 - INFO - Connect to DB
Tue, 21 Jan 2020 10:46:27 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:46:27 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:46:45 - INFO - Connect to DB
Tue, 21 Jan 2020 10:46:45 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:46:45 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:47:24 - INFO - Connect to DB
Tue, 21 Jan 2020 10:47:24 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:47:24 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:48:28 - INFO - Connect to DB
Tue, 21 Jan 2020 10:48:28 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:48:28 - INFO - Failed on TRIZMA DB import at: 2020-01-21_10-10-56, for following calling party: 49306042184, for agent id: trz_asilni, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_asilni',                                 '49306042184','','Nicht übermittelt','49306042184_Wednesday, January 15, 2020_12:58:18 PM','ANA_SILNI')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Tue, 21 Jan 2020 10:48:28 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:48:59 - INFO - Connect to DB
Tue, 21 Jan 2020 10:48:59 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:48:59 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:49:04 - INFO - Connect to DB
Tue, 21 Jan 2020 10:49:04 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:49:04 - INFO - Failed on TRIZMA DB import at: 2020-01-21_10-10-56, for following calling party: 4948112081161, for agent id: trz_asilni, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_asilni',                                 '4948112081161','','Nicht übermittelt','4948112081161_Wednesday, January 15, 2020_2:19:58 PM','ANA_SILNI')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Tue, 21 Jan 2020 10:49:04 - INFO - 123TV DB import
Tue, 21 Jan 2020 10:49:51 - INFO - Connect to DB
Tue, 21 Jan 2020 10:49:51 - INFO - TRIZMA DB import
Tue, 21 Jan 2020 10:49:51 - INFO - 123TV DB import
