Mon, 30 Dec 2019 07:23:13 - INFO - Connect to DB
Mon, 30 Dec 2019 07:23:13 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:23:13 - INFO - Failed on TRIZMA DB import at: 2019-12-30_07-20-50, for following calling party: 4980516014792, for agent id: trz_sstankovic, with error:(pyodbc.DataError) ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated. (8152) (SQLExecDirectW)')
[SQL: insert into records values('CC2Servicenummer','Belgrad','Nicht übermittelt','trz_sstankovic',                                  '4980516014792','','Nicht übermittelt','4980516014792_Wednesday, December 11, 2019_6:38:48 PM')]
(Background on this error at: http://sqlalche.me/e/9h9h)
Mon, 30 Dec 2019 07:23:13 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:23:32 - INFO - Connect to DB
Mon, 30 Dec 2019 07:23:32 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:23:32 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:28:53 - INFO - Connect to DB
Mon, 30 Dec 2019 07:28:53 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:28:53 - INFO - 123TV DB import
Mon, 30 Dec 2019 07:29:03 - INFO - Connect to DB
Mon, 30 Dec 2019 07:29:03 - INFO - TRIZMA DB import
Mon, 30 Dec 2019 07:29:03 - INFO - 123TV DB import
